### ISSUE TITLE
Container won't start because image indiehosters/osticket doesn't exist

### ISSUE THREAD

**Issue by kler** [indiehosters/osticket#1]
After creating the network `lb_web` and running `docker-compose up` I get:

    ERROR: repository indiehosters/osticket not found: does not exist or no pull access

**Comment by pierreozoux** [comment]
Sorry the image is here: https://github.com/indiehosters/docker-osticket

You probably have to build it yourself (I have to add it to the hub...)

**Comment by kler** [comment]
Thx.
Perhaps you could update the docker-compose.yml as well?
